/**
 * HTML Export Engine for Bentoblocks
 *
 * Converts Page/Section/Component architecture to standalone HTML
 * with embedded CSS and Google Fonts integration.
 *
 * @module lib/export/htmlExporter
 */

import { Page, Section, Component } from '@/types/canvas.types';

/**
 * Export a complete Page to standalone HTML
 *
 * @param page - Page object with sections and components
 * @returns Complete HTML document as string
 */
export function exportToHTML(page: Page): string {
  const sections = page.sections.sort((a, b) => a.order - b.order);

  const sectionsHTML = sections.map(section => renderSection(section)).join('\n\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHTML(page.metadata?.title || 'Bentoblocks Site')}</title>
  ${page.metadata?.description ? `<meta name="description" content="${escapeHTML(page.metadata.description)}">` : ''}
  ${page.metadata?.favicon ? `<link rel="icon" href="${escapeHTML(page.metadata.favicon)}">` : ''}
  ${generateGoogleFontsLink(page)}
  <style>${generateCSS(page)}</style>
</head>
<body>
  ${sectionsHTML}
</body>
</html>`;
}

/**
 * Render a Section to HTML
 */
function renderSection(section: Section): string {
  const layoutClass = getLayoutClass(section.layout);
  const componentsHTML = section.children
    .map(c => renderComponent(c, section.layout))
    .join('\n    ');

  const sectionStyles = getInlineStyles(section.style);

  return `  <section
    id="section-${section.id}"
    class="${layoutClass} section-${section.variant}"
    ${sectionStyles ? `style="${sectionStyles}"` : ''}
  >
    ${componentsHTML}
  </section>`;
}

/**
 * Render a Component to HTML
 */
function renderComponent(component: Component, parentLayout: any): string {
  const positionStyle = getPositionStyle(component.position, parentLayout);
  const componentStyles = getComponentStyles(component.style);
  const styleAttr = [positionStyle, componentStyles].filter(Boolean).join('; ');

  switch (component.type) {
    case 'heading': {
      const level = component.content.level;
      return `<h${level} ${styleAttr ? `style="${styleAttr}"` : ''}>${escapeHTML(component.content.text)}</h${level}>`;
    }

    case 'text':
      return `<div class="text-content" ${styleAttr ? `style="${styleAttr}"` : ''}>${component.content.body}</div>`;

    case 'button': {
      const variantClass = `btn-${component.content.variant}`;
      return `<a href="${escapeHTML(component.content.url)}" class="btn ${variantClass}" ${styleAttr ? `style="${styleAttr}"` : ''}>
        ${escapeHTML(component.content.text)}
      </a>`;
    }

    case 'image':
      return `<figure ${styleAttr ? `style="${styleAttr}"` : ''}>
        <img src="${escapeHTML(component.content.src)}" alt="${escapeHTML(component.content.alt)}" ${component.content.objectFit ? `style="object-fit: ${component.content.objectFit}"` : ''} />
        ${component.content.caption ? `<figcaption>${escapeHTML(component.content.caption)}</figcaption>` : ''}
      </figure>`;

    case 'link':
      return `<a href="${escapeHTML(component.content.url)}" class="link-component" ${styleAttr ? `style="${styleAttr}"` : ''}>
        <span class="link-text">${escapeHTML(component.content.text)}</span>
        ${component.content.description ? `<span class="link-desc">${escapeHTML(component.content.description)}</span>` : ''}
      </a>`;

    case 'spacer':
      return `<div class="spacer" style="height: ${component.content.height}px;"></div>`;

    case 'divider':
      return `<hr style="border: none; height: ${component.content.thickness || 2}px; background: ${component.content.color || '#e5e7eb'}; margin: 1rem 0;" />`;

    default:
      return '';
  }
}

/**
 * Get layout CSS class based on layout configuration
 */
function getLayoutClass(layout: any): string {
  if (layout.type === 'stack') {
    return `layout-stack layout-stack-${layout.direction || 'vertical'}`;
  } else if (layout.type === 'grid') {
    return `layout-grid layout-grid-${layout.columns || 2}`;
  } else if (layout.type === 'absolute') {
    return `layout-absolute`;
  }
  return '';
}

/**
 * Generate complete CSS for the page
 */
function generateCSS(page: Page): string {
  // Extract all custom styles from sections and components
  const customStyles = extractCustomStyles(page);

  return `
/* ============================================================================
   BENTOBLOCKS EXPORTED STYLES
   Generated by Bentoblocks HTML Exporter
   ============================================================================ */

/* Reset & Base Styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', sans-serif;
  line-height: 1.6;
  color: #1f2937;
  background: #ffffff;
}

/* ============================================================================
   LAYOUT SYSTEM - Stack (Flexbox)
   ============================================================================ */

.layout-stack {
  display: flex;
  padding: ${page.sections[0]?.layout.padding || '2rem'};
}

.layout-stack-vertical {
  flex-direction: column;
  gap: ${page.sections[0]?.layout.gap || 16}px;
}

.layout-stack-horizontal {
  flex-direction: row;
  gap: ${page.sections[0]?.layout.gap || 16}px;
  flex-wrap: wrap;
}

/* ============================================================================
   LAYOUT SYSTEM - Grid
   ============================================================================ */

.layout-grid {
  display: grid;
  gap: ${page.sections[0]?.layout.gap || 32}px;
  padding: 2rem;
}

.layout-grid-1 { grid-template-columns: 1fr; }
.layout-grid-2 { grid-template-columns: repeat(2, 1fr); }
.layout-grid-3 { grid-template-columns: repeat(3, 1fr); }
.layout-grid-4 { grid-template-columns: repeat(4, 1fr); }
.layout-grid-5 { grid-template-columns: repeat(5, 1fr); }
.layout-grid-6 { grid-template-columns: repeat(6, 1fr); }

/* ============================================================================
   LAYOUT SYSTEM - Absolute
   ============================================================================ */

.layout-absolute {
  position: relative;
  min-height: 400px;
  padding: 2rem;
}

/* ============================================================================
   SECTION VARIANTS
   ============================================================================ */

.section-navbar {
  padding: 1rem 2rem;
  background: #ffffff;
  border-bottom: 1px solid #e5e7eb;
  position: sticky;
  top: 0;
  z-index: 100;
}

.section-hero {
  padding: 4rem 2rem;
  min-height: 500px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

.section-content {
  padding: 3rem 2rem;
  background: #ffffff;
}

.section-features {
  padding: 3rem 2rem;
  background: #f9fafb;
}

.section-gallery {
  padding: 3rem 2rem;
  background: #ffffff;
}

.section-testimonials {
  padding: 3rem 2rem;
  background: #f3f4f6;
}

.section-cta {
  padding: 4rem 2rem;
  background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
  color: white;
  text-align: center;
}

.section-footer {
  padding: 2rem;
  background: #1f2937;
  color: #9ca3af;
  text-align: center;
}

/* ============================================================================
   COMPONENT STYLES
   ============================================================================ */

/* Buttons */
.btn {
  display: inline-block;
  padding: 0.75rem 1.5rem;
  text-decoration: none;
  border-radius: 0.5rem;
  font-weight: 600;
  transition: all 0.2s ease;
  cursor: pointer;
  border: 2px solid transparent;
  text-align: center;
}

.btn-filled {
  background: #3B82F6;
  color: white;
  border-color: #3B82F6;
}

.btn-filled:hover {
  background: #2563EB;
  border-color: #2563EB;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
}

.btn-outlined {
  background: transparent;
  color: #3B82F6;
  border-color: #3B82F6;
}

.btn-outlined:hover {
  background: #3B82F6;
  color: white;
  transform: translateY(-2px);
}

.btn-text {
  background: transparent;
  color: #3B82F6;
  border: none;
  padding: 0.5rem 1rem;
}

.btn-text:hover {
  background: rgba(59, 130, 246, 0.1);
}

/* Text Content */
.text-content {
  line-height: 1.8;
  color: inherit;
}

.text-content p {
  margin-bottom: 1rem;
}

.text-content a {
  color: #3B82F6;
  text-decoration: underline;
}

.text-content a:hover {
  color: #2563EB;
}

/* Images */
figure {
  margin: 0;
  overflow: hidden;
}

figure img {
  width: 100%;
  height: auto;
  display: block;
  border-radius: 0.5rem;
  transition: transform 0.3s ease;
}

figure:hover img {
  transform: scale(1.05);
}

figcaption {
  margin-top: 0.5rem;
  text-align: center;
  font-size: 0.875rem;
  color: #6B7280;
  font-style: italic;
}

/* Links */
.link-component {
  display: inline-flex;
  flex-direction: column;
  text-decoration: none;
  color: #3B82F6;
  transition: color 0.2s ease;
}

.link-component:hover {
  color: #2563EB;
}

.link-text {
  font-weight: 600;
  text-decoration: underline;
}

.link-desc {
  font-size: 0.875rem;
  color: #6B7280;
  margin-top: 0.25rem;
}

/* Spacer */
.spacer {
  width: 100%;
}

/* Typography */
h1, h2, h3, h4, h5, h6 {
  font-weight: 700;
  line-height: 1.2;
  margin-bottom: 0.5rem;
  color: inherit;
}

h1 { font-size: 3rem; }
h2 { font-size: 2.25rem; }
h3 { font-size: 1.875rem; }
h4 { font-size: 1.5rem; }
h5 { font-size: 1.25rem; }
h6 { font-size: 1rem; }

/* ============================================================================
   RESPONSIVE DESIGN
   ============================================================================ */

/* Tablet (810px and below) */
@media (max-width: 810px) {
  .layout-stack-horizontal {
    flex-direction: column;
  }

  .layout-grid {
    grid-template-columns: 1fr !important;
  }

  .section-hero {
    padding: 3rem 1.5rem;
    min-height: 400px;
  }

  .section-content,
  .section-features,
  .section-gallery,
  .section-testimonials,
  .section-cta {
    padding: 2rem 1.5rem;
  }

  h1 { font-size: 2.25rem; }
  h2 { font-size: 1.875rem; }
  h3 { font-size: 1.5rem; }
}

/* Mobile (480px and below) */
@media (max-width: 480px) {
  .layout-stack,
  .layout-grid,
  .layout-absolute {
    padding: 1rem;
  }

  .section-hero {
    padding: 2rem 1rem;
    min-height: 300px;
  }

  .section-content,
  .section-features,
  .section-gallery,
  .section-testimonials,
  .section-cta {
    padding: 1.5rem 1rem;
  }

  h1 { font-size: 1.875rem; }
  h2 { font-size: 1.5rem; }
  h3 { font-size: 1.25rem; }

  .btn {
    padding: 0.625rem 1.25rem;
    font-size: 0.875rem;
  }
}

${customStyles}
  `.trim();
}

/**
 * Extract custom styles from page sections and components
 */
function extractCustomStyles(page: Page): string {
  // This can be expanded to generate custom CSS classes
  // based on unique style combinations in the page
  return '/* Custom component styles */';
}

/**
 * Generate Google Fonts link tag
 */
function generateGoogleFontsLink(page: Page): string {
  const fonts = new Set<string>();

  // Collect all unique fonts from the page
  page.sections.forEach(section => {
    if (section.style.fontFamily) {
      fonts.add(section.style.fontFamily);
    }

    section.children.forEach(component => {
      if (component.style.fontFamily) {
        fonts.add(component.style.fontFamily);
      }
    });
  });

  if (fonts.size === 0) return '';

  const families = Array.from(fonts).map(f =>
    `family=${f.replace(/ /g, '+')}:wght@400;600;700`
  ).join('&');

  return `<link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?${families}&display=swap" rel="stylesheet">`;
}

/**
 * Get position-specific inline styles
 */
function getPositionStyle(position: any, parentLayout: any): string {
  const styles: string[] = [];

  if (position.type === 'absolute' && position.absolute) {
    styles.push('position: absolute');
    styles.push(`left: ${position.absolute.x}px`);
    styles.push(`top: ${position.absolute.y}px`);
  }

  if (parentLayout.type === 'grid' && position.grid) {
    if (position.grid.column) {
      styles.push(`grid-column: ${position.grid.column}`);
    }
    if (position.grid.row) {
      styles.push(`grid-row: ${position.grid.row}`);
    }
  }

  return styles.join('; ');
}

/**
 * Get component-specific inline styles
 */
function getComponentStyles(style: any): string {
  const styles: string[] = [];

  if (style.backgroundColor) styles.push(`background-color: ${style.backgroundColor}`);
  if (style.textColor) styles.push(`color: ${style.textColor}`);
  if (style.fontFamily) styles.push(`font-family: '${style.fontFamily}', sans-serif`);
  if (style.fontSize) styles.push(`font-size: ${style.fontSize}`);
  if (style.fontWeight) styles.push(`font-weight: ${style.fontWeight}`);
  if (style.padding) styles.push(`padding: ${style.padding}`);
  if (style.margin) styles.push(`margin: ${style.margin}`);
  if (style.borderRadius) styles.push(`border-radius: ${style.borderRadius}`);

  return styles.join('; ');
}

/**
 * Get section-specific inline styles
 */
function getInlineStyles(style: any): string {
  const styles: string[] = [];

  if (style.backgroundColor) styles.push(`background-color: ${style.backgroundColor}`);
  if (style.textColor) styles.push(`color: ${style.textColor}`);
  if (style.padding) styles.push(`padding: ${style.padding}`);
  if (style.fontFamily) styles.push(`font-family: '${style.fontFamily}', sans-serif`);

  return styles.join('; ');
}

/**
 * Escape HTML special characters to prevent XSS
 */
function escapeHTML(str: string): string {
  if (!str) return '';

  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
